name: CI

on:
  push:
    branches:
      - "main"
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          no-test: "true"
          allow-dirty: "true"
          secrets: |
            CLIENT_ID = '${{ secrets.CLIENT_ID }}'
            CLIENT_SECRET = '${{ secrets.CLIENT_SECRET }}'
            REDIRECT_URI = '${{ secrets.REDIRECT_URI }}'
            REDIS_URI = '${{ secrets.REDIS_URI }}'
            DEPLOY_URI = '${{ secrets.DEPLOY_URI }}'